# Generated by Django 4.2 on 2023-04-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="gest_can_pause",
            new_name="guest_can_pause",
        ),
    ]
