# Generated by Django 4.2 on 2023-04-14 18:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_gest_can_pause_room_guest_can_pause"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="code",
            field=models.CharField(
                default=api.models.generate_unique_code, max_length=8, unique=True
            ),
        ),
    ]
